name: ftest
version: 0.1.0
summary: Flutter Test for Web Socket
description: Flutter Test for Web Socket

confinement: strict
base: core18
grade: stable

slots:
  dbus-ftest: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.example.ftest # adjust accordingly to your app name and

apps:
  ftest:
    command: ftest
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-ftest
parts:
  ftest:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
